# Flash-Next mathematical and complete Engine qualification.
ninfer_add_op_test(ninfer_hyperconnection_test SOURCES ops/test_hyperconnection.cpp LIBRARIES ninfer_ops)
ninfer_add_op_test(ninfer_flash_next_ple_test SOURCES ops/test_flash_next_ple.cpp LIBRARIES ninfer_ops)
ninfer_add_op_test(ninfer_flash_next_moe_test SOURCES ops/test_flash_next_moe.cpp LIBRARIES ninfer_ops)
ninfer_add_op_test(ninfer_flash_next_qsa_test SOURCES ops/test_flash_next_qsa.cpp LIBRARIES ninfer_ops)
ninfer_add_op_test(ninfer_flash_next_gdn_test SOURCES ops/test_flash_next_gdn.cpp LIBRARIES ninfer_ops)
ninfer_add_test(ninfer_qwen3_8_flash_next_real_test
  SOURCES models/qwen3_8_flash_next_125b_a6b/test_engine_real.cpp LIBRARIES ninfer_engine)
set_tests_properties(ninfer_qwen3_8_flash_next_real_test PROPERTIES SKIP_RETURN_CODE 77)
add_test(NAME ninfer_flash_next_performance_report_test
  COMMAND ${Python3_EXECUTABLE} -m unittest tests/test_flash_next_performance.py)
set_tests_properties(ninfer_flash_next_performance_report_test PROPERTIES WORKING_DIRECTORY ${PROJECT_SOURCE_DIR})

ninfer_add_test(ninfer_qwen3_8_flash_next_ple_table_test
  SOURCES models/qwen3_8_flash_next/test_ple_table.cpp LIBRARIES ninfer_model_runtime)
ninfer_add_test(ninfer_qwen3_8_flash_next_load_plan_test
  SOURCES models/qwen3_8_flash_next_125b_a6b/test_load_plan.cpp LIBRARIES ninfer_model_runtime)
set_tests_properties(ninfer_qwen3_8_flash_next_load_plan_test PROPERTIES SKIP_RETURN_CODE 77)
if(NINFER_PERFORMANCE_TRACE)
  ninfer_add_test(ninfer_performance_trace_fixture
    SOURCES performance_trace_fixture.cu LIBRARIES ninfer_ops)
endif()
ninfer_add_test(ninfer_qwen3_8_flash_next_frontend_test
  SOURCES models/qwen3_8_flash_next/test_frontend.cpp LIBRARIES ninfer_model_runtime)
set_tests_properties(ninfer_qwen3_8_flash_next_frontend_test PROPERTIES SKIP_RETURN_CODE 77)
